# Generated by Django 3.0 on 2019-12-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191204_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publication_data',
            new_name='publication_date',
        ),
    ]
